channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.1.0
  - python=3.8.3
  - pip
  - numpy=1.18.5
  - psutil=5.7.0
  - matplotlib=3.2.2
  - pandas=1.0.5
  - scipy=1.5.0
  - scikit-learn=0.23.1
  - pytorch=1.7.0
  - torchvision=0.8.1
  - torchaudio=0.7.0
  - cachetools==5.2.0
  - google-auth==2.9.0
  - grpcio==1.47.0
  - requests-oauthlib==1.3.1
  - rsa==4.8
  - tensorboard==2.3.0
  - tensorboard-plugin-wit==1.8.1